#ifndef LOCALIZATION_H
#define LOCALIZATION_H

#define LS_DEMO_HELLO "Hi!"
#define LS_DEMO_BUTTON_A "A"
#define LS_DEMO_BUTTON_B "B"
#define LS_DEMO_BUTTON_AB "A+B"
//#define LS_DEMO_SHAKE "SCHUETTELN"
#define LS_DEMO_GREAT "OK!"

#endif // LOCALIZATION_H